# Site settings
title: 孤城空间(lujinhong)
email: lu_jin_hong@163.com, lujinhong2@gamil.com
description: > # this means to ignore newlines until "baseurl:"
 good good study, day day up!!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.lujinhong.com" # the base hostname & protocol for your site
github_username:  lujinhong


# Build settings
markdown: redcarpet 
safe: true 
lsi: false 

redcarpet: 
extensions: 
- with_toc_data 
- hard_wrap 
- no_intra_emphasis 
- tables 
- fenced_code_blocks 
- autolink 
